# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ja:
  languageCode: ja
  contentDir: content/ja
  title: ジェイコブ・スカラニ
  params:
    description: ジェイコブ・スカラニのポートフォリオサイトです。
  menu:
    main:
      - name: ホーム
        url: '#about'
        weight: 1
      - name: ポートフォリオ
        url: '#projects'
        weight: 2  
      - name: 連絡
        url: '#contact'
        weight: 3
